# [IOTData]

In [0]:
/****** Object:  Database [IOTData]    Script Date: 1/11/2020 3:58:37 PM ******/
CREATE DATABASE [IOTData]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO
ALTER DATABASE [IOTData] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [IOTData] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IOTData] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IOTData] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IOTData] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IOTData] SET ARITHABORT OFF 
GO
ALTER DATABASE [IOTData] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IOTData] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IOTData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IOTData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IOTData] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IOTData] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IOTData] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IOTData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IOTData] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [IOTData] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IOTData] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [IOTData] SET  MULTI_USER 
GO
ALTER DATABASE [IOTData] SET ENCRYPTION ON
GO
ALTER DATABASE [IOTData] SET QUERY_STORE = ON
GO
ALTER DATABASE [IOTData] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Customers]

In [0]:
/****** Object:  Table [dbo].[Customers]    Script Date: 1/11/2020 3:58:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CustomerName] [varchar](50) NULL,
	[CustomerID] [varchar](50) NULL,
	[HouseNumber] [int] NULL,
	[StreetName] [varchar](50) NULL,
	[Town] [varchar](50) NULL,
	[State] [varchar](50) NULL,
	[Lat] [real] NULL,
	[Long] [real] NULL,
	[WaterSensorID] [varchar](50) NULL,
	[ElectrictySensorID] [varchar](50) NULL,
	[GasSensorID] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
	[Username] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[HouseSize] [varchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[ElectricitySensorFile]

In [0]:
/****** Object:  Table [dbo].[ElectricitySensorFile]    Script Date: 1/11/2020 3:58:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ElectricitySensorFile](
	[RecordDate] [varchar](50) NULL,
	[ElectricityUsageKw/h] [float] NULL,
	[CustomerID] [varchar](50) NULL,
	[SensorID] [varchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[GasSensorFile]

In [0]:
/****** Object:  Table [dbo].[GasSensorFile]    Script Date: 1/11/2020 3:58:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GasSensorFile](
	[RecordDate] [varchar](50) NULL,
	[GasUsageMJ/H] [float] NULL,
	[CustomerID] [varchar](50) NULL,
	[SensorID] [varchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[WaterSensorFile]

In [0]:
/****** Object:  Table [dbo].[WaterSensorFile]    Script Date: 1/11/2020 3:58:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WaterSensorFile](
	[RecordDate] [varchar](50) NULL,
	[WaterUsageL/h] [smallint] NULL,
	[CustomerID] [varchar](50) NULL,
	[SensorID] [varchar](50) NULL
) ON [PRIMARY]
GO

# [IOTData]

In [0]:
ALTER DATABASE [IOTData] SET  READ_WRITE 
GO